### ISSUE TITLE
What's the version of SWMM this API supported?

### ISSUE THREAD

**Issue by superchen14** [bemcdonnell/SWMMOutputAPI#3]
@bemcdonnell , I have tried your API to get info from report file created by swmm5.exe, but it seems that code will throw exception when get subcatchmentids. My swmm version is 5.1.010

**Comment by bemcdonnell** [comment]
@superchen14, thanks for trying out this tool.  This is still under active development and the most stable branch is the LargeFS-32.  I have tested with SWMM *.out files back to SWMM version 5.0.22 and haven't had any issues.  I suggest compiling the LargeFS-32 branch.  I am finishing up the "pollutant functions" - once they are ready and tested I will merge these changes into master.

**Comment by superchen14** [comment]
Thanks! @bemcdonnell

**Comment by superchen14** [comment]
@bemcdonnell , thanks for the reply. But finally I found out the issue is my report file, not your code. Sorry for the mislead.
