### ISSUE TITLE
outputAPI_winx86.dll

### ISSUE THREAD

**Issue by lboutin** [bemcdonnell/SWMMOutputAPI#7]
I appologize if this is a dump question, but where can I find documentation to compile the outputAPI_winx86.dll library required for the package to work? 

Maybe the setting for compiling are so straightforward that it doesn't requires documentation?

Thanks!

**Comment by bemcdonnell** [comment]
@lboutin,

Sorry for the delay here!  We are no longer maintaining that package.  We have moved to a newer Output API that can be found here: https://github.com/OpenWaterAnalytics/swmm-python/releases/tag/v0.3.0-dev1

I've attached a small code snippet on how to use this.  Let me know if this helps!

[read_swwm.py.zip](https://github.com/bemcdonnell/SWMMOutputAPI/files/4370370/read_swwm.py.zip)

**Comment by lboutin** [comment]
Thanks so much!

I'll move any additional comments to the other repo.

**Comment by bemcdonnell** [comment]
Awesome!
